import type { CombatantTemplate } from './templates'

// Joe's current party (curated to “buff/debuff-ish” spells to track in combat).
// You can edit these in the Templates tab.

export const DEFAULT_PARTY_TEMPLATES: CombatantTemplate[] = [
  {
    id: 'tpl_burt',
    name: 'Burt',
    side: 'PC',
    maxHP: 51,
    ac: 15,
    notes: '',
    resistances: {},
    conditions: [],
    buffLibrary: [
      'Bless',
      'Sanctuary',
      'False Life',
      'Beacon of Hope',
      'Water Walk',
      'Blindness/Deafness',
      'Ray of Enfeeblement',
      'Ray of Sickness',
      'Chill Touch',
      'Guiding Bolt',
      'Spirit Guardians',
      'Dispel Magic',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl_georgie',
    name: 'Georgie',
    side: 'PC',
    maxHP: 40,
    ac: 15,
    notes: '',
    resistances: {},
    conditions: [],
    buffLibrary: [
      "Hunter's Mark",
      'Longstrider',
      'Jump',
      'Magic Weapon',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl_qwyx',
    name: 'Qwyx',
    side: 'PC',
    maxHP: 64,
    ac: 16,
    notes: '',
    resistances: {},
    conditions: [],
    buffLibrary: [
      'Ensnaring Strike',
      'Lesser Restoration',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl_urgoth',
    name: 'Urgoth',
    side: 'PC',
    maxHP: 45,
    ac: 11,
    notes: 'Find Steed (Lamorna)',
    resistances: {},
    conditions: [],
    buffLibrary: [
      'Hex',
      'Faerie Fire',
      'Hypnotic Pattern',
      'Sleep',
      'Charm Person',
      'Calm Emotions',
      'Misty Step',
      'Levitate',
      'Blink',
      'Phantasmal Force',
      'Plant Growth',
      'Water Breathing',
      'Mind Sliver',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl_ven',
    name: 'Ven',
    side: 'PC',
    maxHP: 32,
    ac: 14,
    notes: '',
    resistances: {},
    conditions: [],
    buffLibrary: [
      'Mage Armor',
      'Flame Blade',
      'Ray of Frost',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
